server:
  port: 8081

spring:
  profiles:
    active: dev  # Ensures the 'dev' profile is active
    application:
      name: stocks-service management # Name of the application

  datasource:
    url: jdbc:postgresql://postgres_container:5432/stocks_db  #  Ensure the DB exists and change to your DB host
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP-Pool

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 50
        format_sql: true
        show_sql: true
        cache.use_second_level_cache: false

  sql:
    init:
      mode: always  # Ensures schema and data.sql files are executed at startup

logging:
  level:
    org.springframework: INFO  #  Set logging level to INFO (can be DEBUG if needed)

# Enable Swagger UI
# Enable OpenAPI Documentation
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    url: /v3/api-docs
    operationsSorter: alpha
    tryItOutEnabled: true